workspace:
  base: /drone
  path: src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/${DRONE_MACHINE}/${DRONE_HOSTNAME}
clone:
  git:
    image: plugins/git
    volumes:
    - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
pipeline:
  build:
    image: maven
    commands:
      - env
      - mvn clean test
    volumes:
      - /root/.m2:/root/.m2
      - /root/.gnupg:/root/.gnupg
      - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
